apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mecaniqa
resources:
  - namespace.yaml
  - iot.yaml
  - prometheus.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
